version: "3"

services:
    nominatim:
        image: mediagis/nominatim:5.1
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/5.1#configuration for more options
            PBF_URL: https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf
            NOMINATIM_PASSWORD: pass
            IMPORT_STYLE: street
            POSTGRES_MAINTENANCE_WORK_MEM: 4GB
            POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
        volumes:
            - ./nominatim-data:/var/lib/postgresql/16/main
        shm_size: 1gb

